// <!--
document.write('<div id="footer">&nbsp;');
document.write('<a class="loimy" href="#_ddrv1">&nbsp;А&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv2">&nbsp;Аь&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv3">&nbsp;Б&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv4">&nbsp;В&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv5">&nbsp;Г&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv6">&nbsp;ГI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv7">&nbsp;Д&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv8">&nbsp;Е&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv9">&nbsp;Ж&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv10">&nbsp;ЖI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv11">&nbsp;З&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv12">&nbsp;ЗI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv13">&nbsp;И&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv14">&nbsp;Й&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv15">&nbsp;К&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv16">&nbsp;Кх&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv17">&nbsp;Къ&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv18">&nbsp;КI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv19">&nbsp;Л&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv20">&nbsp;М&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv21">&nbsp;Н&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv22">&nbsp;О&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv23">&nbsp;П&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv24">&nbsp;Р&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv25">&nbsp;С&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv26">&nbsp;Т&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv27">&nbsp;ТI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv28">&nbsp;У&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv29">&nbsp;Ф&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv30">&nbsp;Х&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv31">&nbsp;Хь&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv32">&nbsp;ХI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv33">&nbsp;Ц&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv34">&nbsp;ЦI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv35">&nbsp;Ч&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv36">&nbsp;ЧI&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv37">&nbsp;Ш&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv38">&nbsp;Э&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv39">&nbsp;Ю&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv40">&nbsp;Я&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv41">&nbsp;Яь&nbsp;</a>');
document.write('<a class="loimy" href="#_ddrv42">&nbsp;I&nbsp;</a>');
document.write('&nbsp;</div>');
//-->
